image: ghcr.io/cirruslabs/flutter:3.22.2

stages:
  - build
  - deploy

cache:
  paths:
    - flutter_app/.pub-cache

build:
  stage: build
  script:
    - cd flutter_app
    - flutter pub get
    - flutter build web
  artifacts:
    paths:
      - flutter_app/build/web
    expire_in: 1 week

pages:
  stage: deploy
  script:
    - mv flutter_app/build/web public
  artifacts:
    paths:
      - public